package me.ai.training.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import me.ai.training.dto.Response;
import me.ai.training.service.AiCafeChatClientService;
import me.ai.training.service.AiCafeChatModelService;
import me.ai.training.service.AiCafeUsingRestTemplateService;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


/**
 * @author Rohit Muneshwar
 *
 * Controller class to consumer AI services provided by OpenAI platform.
 * This class demonstrates the usage of interacting with AiCafe via both RestTemplate and Spring AI's ChatClient/ChatModel.
 * So, it has dependency of AiCafeChatClientService (uses ChatClient), AiCafeChatModelService (uses ChatModel) and AiCafeUsingRestTemplateService (uses RestTemplate).
 */
@Tag(name = "Lab1: Integration of OpenAI to SpringBoot", description = """
        Examples implemented as a part of practicing integration of Spring AI.
        This shows using AiCafe as an OpenAI service provider using RestTemplate, Spring AI's ChatClient and ChatModel.
        """)
@RestController
public class BasicIntegrationController {
    private final AiCafeChatClientService aiCafeChatClientService;
    private final AiCafeUsingRestTemplateService aiCafeUsingRestTemplate;
    private final AiCafeChatModelService aiCafeChatModelService;

    public BasicIntegrationController(AiCafeChatModelService aiCafeChatModelService, AiCafeChatClientService aiCafeChatClientService, AiCafeUsingRestTemplateService aiCafeUsingRestTemplate){
        this.aiCafeChatClientService = aiCafeChatClientService;
        this.aiCafeChatModelService = aiCafeChatModelService;
        this.aiCafeUsingRestTemplate = aiCafeUsingRestTemplate;
    }

    /**
     * Returns the response generated by AiCafeService which uses Spring AI's ChatClient to interact with Aicafe.
     *
     * This endpoint demonstrates the usage of ChatClient to get the response from LLM.
     *
     * @param message
     * @return
     */
    @Operation(summary = "ChatClient:: Default Landing page which tells who is this", description = """
            By default tells who is this. you can also send specific input to this endpoint.
            This endpoint demonstrates the usage of ChatClient to get the response from LLM.
            """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "returns response to the asked query",
            content = @Content(schema = @Schema(implementation = String.class)))
    })
    @GetMapping(value = "/")
    public String defaultJoke(@RequestParam(value = "message", defaultValue = "Tell me something about yourself.") String message) {
        return aiCafeChatClientService.createJoke(message);
    }

    /**
     * Returns the response generated by AiCafeService which uses Spring AI's ChatModel to interact with Aicafe.
     *
     * This endpoint demonstrates the usage of ChatModel to get the response from LLM.
     * It also demonstrates the usages of SystemMessage, AssistantMessage and UserMessage.
     *
     * @param message
     * @return
     */
    @Operation(summary = "ChatModel::Ask specific request", description = """
            This endpoint demonstrates the usage of ChatModel to get the response from LLM.
            It also demonstrates the usages of SystemMessage, AssistantMessage and UserMessage.
            System message: define the purpose, behavior, tone or role of AI model
            Assistant message: represent some previous response as an assistance to the AI
            User message: represent actual input/question/instruction to AI
            
            Order of execution:
            System(behavior/roles) -> Assistant(previous context) -> User messages(your query)
            """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = """
                    It returns response to the asked query.
                    It also demonstrates the usages of SystemMessage, AssistantMessage and UserMessage.
                    """,
                    content = @Content(schema = @Schema(implementation = String.class)))
    })
    @GetMapping(value = "/ask")
    public String askMeAnything(@RequestParam(value = "message", defaultValue = "Tell me something about yourself.") String message) {
        return aiCafeChatModelService.askMeAnything(message);
    }

    /**
     * Returns the response generated by AiCafeUsingRestTemplate which uses RestTemplate to interact with Aicafe.
     *
     * This endpoint demonstrates the usage of RestTemplate to get the response from LLM.
     *
     * @param message
     * @return
     */
    @Operation(summary = "RestTemplate::Ask a joke", description = """
    This endpoint demonstrates the usage of RestTemplate to get the response from LLM.
    e.g. Tell me a dad joke about Artificial Intelligence.
    """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "returns response to the asked query",
                    content = @Content(schema = @Schema(implementation = Response.class)))
    })
    @GetMapping(value = "/joke", produces= MediaType.APPLICATION_JSON_VALUE)
    public Response createJoke(@RequestParam(value = "message", defaultValue = "Tell me a dad joke about Artificial Intelligence.") String message) {
        return aiCafeUsingRestTemplate.createJoke(message);
    }
}
