package com.edu.spring.ai.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import com.edu.spring.ai.dto.Response;
import com.edu.spring.ai.service.AiCafeChatClientService;
import com.edu.spring.ai.service.AiCafeChatModelService;
import com.edu.spring.ai.service.AiCafeUsingRestTemplateService;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


/**
 * @author Rohit Muneshwar
 * Examples implemented as a part of practicing integration of Spring AI.
 * In this example RestTemplate, Spring AI's ChatClient and ChatModel and used to get the response from LLM model.
 *
 */
@Tag(name = "Lab1: Integration of OpenAI to SpringBoot", description = """
        In this example apis RestTemplate, Spring AI's ChatClient and ChatModel are used to get the response from LLM.
        """)
@RestController
@RequestMapping("/chat")
public class BasicChatController {
    private final AiCafeChatClientService aiCafeChatClientService;
    private final AiCafeUsingRestTemplateService aiCafeUsingRestTemplate;
    private final AiCafeChatModelService aiCafeChatModelService;

    public BasicChatController(AiCafeChatModelService aiCafeChatModelService, AiCafeChatClientService aiCafeChatClientService, AiCafeUsingRestTemplateService aiCafeUsingRestTemplate){
        this.aiCafeChatClientService = aiCafeChatClientService;
        this.aiCafeChatModelService = aiCafeChatModelService;
        this.aiCafeUsingRestTemplate = aiCafeUsingRestTemplate;
    }

    /**
     * Returns the response generated by AiCafeService which uses Spring AI's ChatClient to interact with Aicafe.
     *
     * This endpoint demonstrates the usage of ChatClient to get the response from LLM.
     *
     * @param message
     * @return
     */
    @Operation(summary = "ChatClient::Ask me anything", description = """
            By default tells who is this. you can also send specific input to this endpoint.
            This endpoint demonstrates the usage of ChatClient to get the response from LLM.
            """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "returns response to the asked query",
            content = @Content(schema = @Schema(implementation = String.class)))
    })
    @GetMapping(value = "/ask-me")
    public String aksMe(@RequestParam(value = "message", defaultValue = "Tell me something about yourself.") String message) {
        return aiCafeChatClientService.createJoke(message);
    }

    /**
     * Returns the response generated by AiCafeService which uses Spring AI's ChatModel to interact with Aicafe.
     *
     * This endpoint demonstrates the usage of ChatModel to get the response from LLM.
     * It also demonstrates the usages of SystemMessage, AssistantMessage and UserMessage.
     *
     * @param message
     * @return
     */
    @Operation(summary = "ChatModel::Text me any specific requests", description = """
            This endpoint demonstrates the usage of ChatModel to get the response from LLM.
            It implementation uses SystemMessage, AssistantMessage and UserMessage.
            System message: define the purpose, behavior, tone or role of AI model
            Assistant message: represent some previous response as an assistance to the AI
            User message: represent actual input/question/instruction to AI
            
            Order of execution:
            System(behavior/roles) -> Assistant(previous context) -> User messages(your query)
            """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = """
                    It returns response to the asked query.
                    It also demonstrates the usages of SystemMessage, AssistantMessage and UserMessage.
                    """,
                    content = @Content(schema = @Schema(implementation = String.class)))
    })
    @GetMapping(value = "/ask")
    public String askMeAnything(@RequestParam(value = "message", defaultValue = "Tell me something about yourself.") String message) {
        return aiCafeChatModelService.askMeAnything(message);
    }

    /**
     * Returns the response generated by AiCafeUsingRestTemplate which uses RestTemplate to interact with Aicafe.
     *
     * This endpoint demonstrates the usage of RestTemplate to get the response from LLM.
     *
     * @param message
     * @return
     */
    @Operation(summary = "RestTemplate::Ask a joke", description = """
    This endpoint demonstrates the usage of RestTemplate to get the response from LLM.
    e.g. Tell me a dad joke about Artificial Intelligence.
    """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "returns response to the asked query",
                    content = @Content(schema = @Schema(implementation = Response.class)))
    })
    @GetMapping(value = "/joke", produces= MediaType.APPLICATION_JSON_VALUE)
    public Response createJoke(@RequestParam(value = "message", defaultValue = "Tell me a dad joke about Artificial Intelligence.") String message) {
        return aiCafeUsingRestTemplate.createJoke(message);
    }
}
