package com.edu.spring.ai.config;

import com.edu.spring.ai.weather.Weather;
import com.edu.spring.ai.weather.WeatherApiService;
import org.springframework.ai.chat.client.advisor.vectorstore.QuestionAnswerAdvisor;
import org.springframework.ai.chat.prompt.ChatOptions;
import org.springframework.ai.document.Document;
import org.springframework.ai.openai.OpenAiChatOptions;
import org.springframework.ai.openai.api.OpenAiAudioApi;
import org.springframework.ai.openai.api.common.OpenAiApiClientErrorException;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.ai.vectorstore.filter.Filter;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBooleanProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Description;

import java.util.List;
import java.util.function.Function;

/**
 * @author Rohit Muneshwar
 * @created on 2/24/2026
 *
 *
 */
@Configuration
public class AiConfig {
    @Bean
    QuestionAnswerAdvisor qaAdvisor(VectorStore vectorStore){
        return QuestionAnswerAdvisor.builder(vectorStore)
                .searchRequest(SearchRequest.builder().topK(5).similarityThreshold(0.3).build())
                .build();
    }

    @Bean
    OpenAiAudioApi openAiAudioApi(@Value("${spring.ai.openai.audio.transcription.base-url}")
                                  String endpoint,
                                  @Value("${spring.ai.openai.api-key}")
                                  String apiKey){
        return new OpenAiAudioApi.Builder()
                .baseUrl(endpoint)
                .apiKey(apiKey)
                .build();
    }


    // FunctionCalling:: Register this function here so that it can be used by LLM
    @Bean
    @Description("Get the weather of the city")
    Function<Weather.Request, Weather.Response> currentWeather(){
        return new WeatherApiService();
    }

    /**
     * Recommendation:
     * Temperature = 0.6 - balanced
     * Maxtokens = 200 - controlled response size
     * topP = 0.9 - good vocabulary
     * frequencyPenalty - 0.4 - avoids repetition
     * presencePenalty - 0.2 - introduce new
     * @return
     */
    @Bean
    ChatOptions openAiChatOptions(){
        // provide OpenAI chat options: controls the response generated by the AI
        return OpenAiChatOptions.builder()
                // creativity(1.5) vs predictability(0.0)
                .temperature(0.7)
                // words+punctuations -> maximum length of response.
                // too high -> cost + latency
                .maxTokens(200)
                // nucleus sampling - controls word choices
                // default - 0.9 -> considers top 90% probability words
                // 1.0 -> considers all possible words
                // 0.5 -> very narrow, safe words only
                .topP(0.9)
                // control repetition of same words.
                // high frequency means less repetition.
                // 0.3 to 0.6 for explanation
                .frequencyPenalty(0.4)
                // encourage with new topics/ideas - control repetition of same concepts.
                // high -> new ideas
                /**
                 * Prompt: Explain Java
                 * PresencePenalty = 0.0 - basics of Java
                 * PresencePenalty= 0.2 (default) - new features of Java
                 */
                .presencePenalty(0.2)
                .build();
    }

    // dummy vector store implementation if opensearch is not enabled
    @Bean
    @ConditionalOnBooleanProperty(prefix = "spring.ai.custom.vectorstore", name = "enabled", havingValue = false)
    VectorStore vectorStore(){
        return new VectorStore() {
            @Override
            public void add(List<Document> list) {

            }

            @Override
            public void delete(List<String> list) {

            }

            @Override
            public void delete(Filter.Expression expression) {

            }

            @Override
            public List<Document> similaritySearch(SearchRequest searchRequest) {
                return List.of();
            }
        };
    }
}
